name: Tests

on: [push]

jobs:
  test:
    environment: Test
    name: Testing sms-providers
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Revert changes into the yarn.lock file
        run: git checkout -- yarn.lock

      - name: Run test
        run: yarn test:ci
        env:
          NODE_ENV: ci
          PHONE_RECIPIENT: ${{ secrets.PHONE_RECIPIENT }}

          MESSAGE_BIRD_API_KEY: ${{ secrets.MESSAGE_BIRD_API_KEY }}

          CLICK_SEND_USER_NAME: ${{ secrets.CLICK_SEND_USER_NAME }}
          CLICK_SEND_API_KEY: ${{ secrets.CLICK_SEND_API_KEY }}

          VONAGE_API_KEY: ${{ secrets.VONAGE_API_KEY }}
          VONAGE_API_SECRET: ${{ secrets.VONAGE_API_SECRET }}
